"""empty message

Revision ID: a54fb0eb0ae2
Revises: 
Create Date: 2018-06-20 22:17:02.121799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54fb0eb0ae2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'beverage_user', 'accounting_report', ['accounting_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'beverage_user', type_='foreignkey')
    # ### end Alembic commands ###
